name: 0.7.1.$(rev:rrrr)

trigger:
  branches:
    include:
    - master

schedules:
- cron: 0 0 * * 0 # 0 - hour | 0 - minute | * - any day | * - any month | 0 - sunday
  displayName: 'Scheduled Build'
  branches:
    include:
      - master
  always: true

variables:
- group: deploy-secrets

stages:
- stage: build_test
  displayName: 'Build + Test'
  jobs:
  - job: build_linux
    displayName: 'Build - Release - Ubuntu (MariaDB + SQL Server + Sqlite)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - script: sudo ./install-deps.sh
      displayName: 'Install build dependencies'
      workingDirectory: 'scripts'
    - script: ./build-linux.sh -c --sqlserver ON --mariadb ON --sqlite ON
      displayName: 'Build'
    - script: ./eoserv_test
      displayName: 'Test'
      workingDirectory: $(Build.SourcesDirectory)/install/test
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'install'
        ArtifactName: 'linux'
        publishLocation: 'Container'

  - job: build_windows
    displayName: 'Build - Release - Windows (MariaDB + SQL Server + Sqlite)'
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: self
      lfs: true
    - task: PowerShell@2
      displayName: 'Install build dependencies'
      inputs:
        filePath: '.\scripts\install-deps.ps1'
        arguments: '-SkipCMake' # CMake is installed on the windows-latest image
    - task: PowerShell@2
      displayName: 'Build'
      inputs:
        filePath: '.\build-windows.ps1'
        arguments: '-Clean -SqlServer ON -MariaDB ON -Sqlite ON'
    - script: .\eoserv_test.exe
      displayName: 'Test'
      workingDirectory: $(Build.SourcesDirectory)\install\test
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'install'
        ArtifactName: 'windows'
        publishLocation: 'Container'

  - job: build_docker
    displayName: 'Docker build'
    dependsOn: build_linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - task: DownloadBuildArtifacts@0
      inputs:
        downloadType: 'single'
        artifactName: 'linux'
        downloadPath: '$(Build.SourcesDirectory)'
    - script: mv linux install
      displayName: 'Rename linux dir -> install'
    - script: chmod +x install/etheos
      displayName: 'Make etheos binary executable'
    - task: Docker@2
      inputs:
        command: login
        containerRegistry: etheos
    - task: Docker@2
      condition: not(or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'Schedule')))
      displayName: 'Build/push etheos image'
      inputs:
        command: buildAndPush
        repository: etheos/dev
        tags: |
          $(Build.BuildNumber)
          latest
    - task: Docker@2
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: 'Push etheos:ci-test image - CI build'
      inputs:
        command: buildAndPush
        repository: etheos/ci-test
        tags: |
          $(Build.BuildNumber)
          latest

  - job: tag_sources
    displayName: 'Tag on success'
    dependsOn: [ 'build_windows', 'build_linux', 'build_docker' ]
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
      persistCredentials: true
    - script: |
        git tag build/$(Build.BuildNumber)
        git push origin build/$(Build.BuildNumber)
      workingDirectory: $(Build.SourcesDirectory)

  - job: deploy
    displayName: 'Deploy to azure'
    dependsOn: [ 'tag_sources' ]
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - script: $(Build.SourcesDirectory)/deploy/deploy.sh CREATE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e dev
      condition: not(eq(variables['Build.Reason'], 'IndividualCI'))
      displayName: 'PR/Manual Builds - Deploy to dev environment'

    - script: $(Build.SourcesDirectory)/deploy/deploy.sh CREATE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e ci-test -g etheos --template-file $(Build.SourcesDirectory)/deploy/etheos-ci-test.json --parameter-file $(Build.SourcesDirectory)/deploy/params-ci-test.json
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: 'CI Builds - Deploy to ci-test environment'
    - script: python3 $(Build.SourcesDirectory)/deploy/test-connection.py ci-test.etheos.moffat.io 8078 9078 10078
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: 'CI Builds - Test connection to server'

    - task: DownloadGitHubRelease@0
      inputs:
        connection: github_oauth
        userRepository: ethanmoffat/EndlessClient
        itemPattern: '**/EOBot.Linux.zip'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(System.ArtifactsDirectory)/EOBot.Linux.zip'
        destinationFolder: $(System.ArtifactsDirectory)/eobot
    - script: | # todo: make this a reusable script file
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/create_accounts.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/create_accounts.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/create_accounts.eob

        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "BotP@ssw0rd" "NewPassword"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "BotP@ssw0rd" "NewPassword"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "BotP@ssw0rd" "NewPassword"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "NewPassword" "BotP@ssw0rd"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "NewPassword" "BotP@ssw0rd"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 numbots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "NewPassword" "BotP@ssw0rd"

        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 numbots=5 script=$(Build.SourcesDirectory)/src/test/integration/login_queue_busy.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 numbots=5 script=$(Build.SourcesDirectory)/src/test/integration/login_queue_busy.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 numbots=5 script=$(Build.SourcesDirectory)/src/test/integration/login_queue_busy.eob
      condition: succeeded()
      displayName: 'Run integration test scripts'
    - script: $(Build.SourcesDirectory)/deploy/deploy.sh DELETE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e ci-test -g etheos --template-file $(Build.SourcesDirectory)/deploy/etheos-ci-test.json --parameter-file $(Build.SourcesDirectory)/deploy/params-ci-test.json
      condition: and(eq(variables['Build.Reason'], 'IndividualCI'), succeededOrFailed())
      displayName: 'CI Builds - Delete ci-test environment'

    - task: DownloadBuildArtifacts@0
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      inputs:
        downloadType: 'single'
        artifactName: 'linux'
        downloadPath: '$(Build.SourcesDirectory)'
    - script: mv linux install
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: 'Rename linux dir -> install'
    - script: chmod +x install/etheos
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: 'Make etheos binary executable'
    - task: Docker@2
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      inputs:
        command: login
        containerRegistry: etheos
    - task: Docker@2
      condition: eq(variables['Build.Reason'], 'IndividualCI')
      displayName: 'Push etheos:test image - CI build'
      inputs:
        command: buildAndPush
        repository: etheos/test
        tags: |
          $(Build.BuildNumber)
          latest
    - script: $(Build.SourcesDirectory)/deploy/deploy.sh CREATE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e test
      condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
      displayName: 'Successful CI Builds - Deploy to test environment'
