name: 0.7.1.$(rev:rrrr)

resources:
  pipelines:
  - pipeline: etheos
    source: etheos
    trigger:
      branches:
        include:
        - master

variables:
- group: deploy-secrets

stages:
- stage: integration_test
  displayName: 'Run Integration Tests'
  jobs:
  - job: deploy
    displayName: 'Deploy to ci-test environment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - script: $(Build.SourcesDirectory)/deploy/deploy.sh CREATE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e ci-test -g etheos --template-file $(Build.SourcesDirectory)/deploy/etheos-ci-test.json --parameter-file $(Build.SourcesDirectory)/deploy/params-ci-test.json
      condition: succeeded()
      displayName: 'CI Builds - Deploy to ci-test environment'
    - script: python3 $(Build.SourcesDirectory)/deploy/test-connection.py ci-test.etheos.moffat.io 8078 9078 10078
      condition: succeeded()
      displayName: 'CI Builds - Test connection to server'

  - job: test
    displayName: 'Run integration tests against ci-test environment'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadGitHubRelease@0
      inputs:
        connection: github_oauth
        userRepository: ethanmoffat/EndlessClient
        itemPattern: '**/EOBot.Linux.zip'
    - task: ExtractFiles@1
      inputs:
        archiveFilePatterns: '$(System.ArtifactsDirectory)/EOBot.Linux.zip'
        destinationFolder: $(System.ArtifactsDirectory)/eobot
    - script: | # todo: make this a reusable script file
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/create_accounts.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/create_accounts.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/create_accounts.eob

        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "BotP@ssw0rd" "NewPassword"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "BotP@ssw0rd" "NewPassword"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "BotP@ssw0rd" "NewPassword"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "NewPassword" "BotP@ssw0rd"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "NewPassword" "BotP@ssw0rd"
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 bots=10 script=$(Build.SourcesDirectory)/src/test/integration/change_passwords.eob -- "NewPassword" "BotP@ssw0rd"

        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=8078 bots=5 script=$(Build.SourcesDirectory)/src/test/integration/login_queue_busy.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=9078 bots=5 script=$(Build.SourcesDirectory)/src/test/integration/login_queue_busy.eob
        $(System.ArtifactsDirectory)/eobot/net6.0/EOBot host=ci-test.etheos.moffat.io port=10078 bots=5 script=$(Build.SourcesDirectory)/src/test/integration/login_queue_busy.eob
      condition: succeeded()
      workingDirectory: $(System.ArtifactsDirectory)
      displayName: 'Run integration test scripts'

  - job: undeploy
    displayName: 'Delete ci-test environment (reduce Azure spend)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: $(Build.SourcesDirectory)/deploy/deploy.sh DELETE -u 55d02cce-765c-4364-a5a6-1328ba987d83 -p $(deployAppSecret) -e ci-test -g etheos --template-file $(Build.SourcesDirectory)/deploy/etheos-ci-test.json --parameter-file $(Build.SourcesDirectory)/deploy/params-ci-test.json
      condition: succeededOrFailed()
      displayName: 'CI Builds - Delete ci-test environment'
